name: Build iOS IPA (TrollStore)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check project files
        run: ls -R

      - name: Install dependencies
        run: flutter pub get
        working-directory: simple_live_app

      - name: Generate iOS project
        run: |
          flutter create .
          cd ios
          pod install
          cd ..
        working-directory: simple_live_app

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign
        working-directory: simple_live_app

      - name: Export IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r dart_simple_live.ipa Payload
        working-directory: simple_live_app

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: dart_simple_live_ipa
          path: build/ios/iphoneos/dart_simple_live.ipa
